### ISSUE TITLE
NullPointerException method void java.util.Timer.cancel()

### ISSUE THREAD

**Issue by iflove** [eclipse/paho.mqtt.android#190]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__

__Android Version Bug Seen on:__

Please also check that if you have found the bug in the Release version (1.1.1) that you check that it also exists in the Snapshot (1.1.2-SNAPSHOT) before raising a bug.

## Description of Bug:
E.g. First open app, then disconnect network，lock screen ，deblocking to connect network ,app crash 

## Console Log output (if available):
```
 java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver@24df226
	    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:873)
	    at android.os.Handler.handleCallback(Handler.java:739)
	    at android.os.Handler.dispatchMessage(Handler.java:95)
	    at android.os.Looper.loop(Looper.java:135)
	    at android.app.ActivityThread.main(ActivityThread.java:5248)
	    at java.lang.reflect.Method.invoke(Native Method)
	    at java.lang.reflect.Method.invoke(Method.java:372)
	    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
	    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
	 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Timer.cancel()' on a null object reference
	    at org.eclipse.paho.client.mqttv3.MqttAsyncClient.stopReconnectCycle(MqttAsyncClient.java:1120)
	    at org.eclipse.paho.client.mqttv3.MqttAsyncClient.reconnect(MqttAsyncClient.java:1057)
	    at org.eclipse.paho.android.service.MqttConnection.reconnect(MqttConnection.java:1049)
	    at org.eclipse.paho.android.service.MqttService.reconnect(MqttService.java:342)
	    at org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(MqttService.java:827)
	    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:863)
	    at android.os.Handler.handleCallback(Handler.java:739) 
	    at android.os.Handler.dispatchMessage(Handler.java:95) 
	    at android.os.Looper.loop(Looper.java:135) 
	    at android.app.ActivityThread.main(ActivityThread.java:5248) 
	    at java.lang.reflect.Method.invoke(Native Method) 
	    at java.lang.reflect.Method.invoke(Method.java:372) 
	    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909) 
	    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704) 
```

**Comment by miketran78727** [comment]
Should now be resolved by: eclipse/paho.mqtt.java#326
Also, see issue #180

**Comment by iflove** [comment]
thanks

**Comment by jpwsutton** [comment]
The Java client has now had it's 1.1.1 service release and is available on both repo.eclipse.org and Maven Central. I recommend updating your dependency for the Java library to 1.1.1 and this issue should be resolved.

**Comment by elsennov** [comment]
I still can't find on Maven for the client https://mvnrepository.com/artifact/org.eclipse.paho/org.eclipse.paho.client.mqttv3

@jpwsutton

**Comment by jpwsutton** [comment]
https://search.maven.org/#artifactdetails%7Corg.eclipse.paho%7Corg.eclipse.paho.client.mqttv3%7C1.1.1%7Ceclipse-plugin

**Comment by elsennov** [comment]
Ah, thank you @jpwsutton !
